FROM python:3.7

# Install dependencies
RUN apt-get update
RUN apt-get install -y nano cron
RUN apt install dos2unix

# Install Python libraries
RUN pip install --upgrade pip
RUN pip install requests pyyaml pyopenssl simplejson
#RUN pip install json pyyaml pyopenssl base64 subprocess
RUN pip install kubernetes

# Copy python files to container
COPY python/sectigo_pycert.py python/renew_entrypoint.py /

# Permissions
RUN dos2unix /renew_entrypoint.py
RUN chmod +x /renew_entrypoint.py 

# Create log file 
RUN touch /var/log/cron.log

ADD renew_cron /etc/cron.d/renew_cron
RUN crontab /etc/cron.d/renew_cron
CMD ["cron", "-f"]