apiVersion: v1
data:
  sslId: MTIzNDU2Cg==
  tls.crt: YWFhYQo=
  tls.key: YWFhYQo=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"abv":"","sslId":"MTIzNDU2Cg==","tls.crt":"YWFhYQo=","tls.key":"YWFhYQo="},"kind":"Secret","metadata":{"annotations":{},"name":"aaaa","namespace":"default"},"type":"Opaque"}
  creationTimestamp: "2020-07-07T11:36:41Z"
  name: my-secret-1
  namespace: default
  resourceVersion: "88911565"
  selfLink: /api/v1/namespaces/default/secrets/aaaa
  uid: 20a73979-c046-11ea-a06d-062165523490
type: Opaque

