apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2020-06-01T18:38:34Z
  name: sectigo-operator-config
  namespace: default
  resourceVersion: "810136"
  uid: 252c4572-eb35-11e7-887b-42010a8002b8
data:
  resourceVersionCompleted: "0"
  namespace: default